import HomePage from "./HomePage"
import ProjectPage from "./ProjectPage"
import SchedulePage from "./SchedulePage"
import KPIPage from "./KPIPage"
import LoginPage from "./LoginPage"
import SignupPage from "./SignupPage"
import ProjectDetails from "./ProjectDetails"
import SettingPage from "./SettingPage"
import PersonalPage from "./PersonalPage"
export { LoginPage, HomePage, ProjectPage, SchedulePage, KPIPage, SignupPage, ProjectDetails, SettingPage, PersonalPage }